<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assertion_Search</name>
   <tag></tag>
   <elementGuidId>26a38157-8073-4cbe-8bcd-2fce08ecf16b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;testData&quot;]/div/div[1]/div/div/div/div/div/div[2]/div/a/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;testData&quot;]/div/div[1]/div/div/div/div/div/div[2]/div/a/h3</value>
   </webElementProperties>
</WebElementEntity>
